version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/Anantgoel0123456/kernel_mido --single-branch -b normal mido
           cd mido
           wget https://github.com/dtyghc/Kernel_workflow/raw/master/Build.sh.old
           chmod a+x ./Build.sh.old
           bash ./Build.sh.old
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
